//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataAccess
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class BookList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookList()
        {
            this.BorrowBookDetails = new HashSet<BorrowBookDetail>();
        }
    
        public int Book_ID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int Category_ID { get; set; }
        
        public virtual BookCategory BookCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<BorrowBookDetail> BorrowBookDetails { get; set; }
    }
}
