//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataAccess
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowBookDetail
    {
        public int BorrowBookDetails_ID { get; set; }
        public int Book_ID { get; set; }
        public int BorrowBook_ID { get; set; }
        [JsonIgnore]
        public virtual BookList BookList { get; set; }
        [JsonIgnore]
        public virtual BorrowBook BorrowBook { get; set; }
    }
}
